import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import AuthLayout from './AuthLayout';
import AuthFormShell, { InputField } from './AuthFormShell';
import { useAuth } from '../../context/AuthContext';
import { authApi } from '../../services/api';

const roleRedirectMap = {
  user: '/user',
  mentor: '/mentor',
  admin: '/admin'
};

export default function OtpVerificationPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { setUser } = useAuth();
  const [form, setForm] = useState({ email: location.state?.email ?? '', otpCode: location.state?.otpCode ?? '' });
  const [status, setStatus] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (location.state?.email) {
      setForm((current) => ({ ...current, email: location.state.email }));
    }
    if (location.state?.otpCode) {
      setForm((current) => ({ ...current, otpCode: location.state.otpCode }));
    }
  }, [location.state]);

  const handleSubmit = async (event) => {
    event.preventDefault();
    setIsSubmitting(true);
    setStatus(null);

    try {
      const response = await authApi.verifyOtp(form);
      setUser(response.user);
      navigate(roleRedirectMap[response.user.role] ?? '/', { replace: true });
    } catch (error) {
      setStatus({ type: 'error', message: error.message });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <AuthLayout
      eyebrow="OTP Verification"
      title="Verify your email address."
      description="Enter the code generated by the backend to activate the account and complete signup."
      footer={
        <div className="flex flex-wrap items-center justify-between gap-3 text-sm">
          <Link className="text-[var(--color-primary)]" to="/login">
            Back to login
          </Link>
          <Link className="text-[var(--color-primary)]" to="/roles">
            Start over
          </Link>
        </div>
      }
    >
      <AuthFormShell
        onSubmit={handleSubmit}
        actionLabel={isSubmitting ? 'Verifying...' : 'Verify code'}
        status={status}
        submitDisabled={isSubmitting}
        fields={
          <>
            <InputField
              label="Email address"
              type="email"
              value={form.email}
              onChange={(event) => setForm({ ...form, email: event.target.value })}
              placeholder="you@example.com"
              required
            />
            <InputField
              label="OTP code"
              value={form.otpCode}
              onChange={(event) => setForm({ ...form, otpCode: event.target.value })}
              placeholder="6-digit code"
              helperText="In development, the code is returned by the signup response."
              required
            />
          </>
        }
      />
    </AuthLayout>
  );
}